
import type { TextFormatConfig, HorizontalAlignment, VerticalAlignment } from './excel-types';
import { parseColumnIdentifier, parseSourceColumns } from './excel-helpers';

// Helper functions for VBScript syntax
function getVbsColor(hex: string): string {
    if (!hex || hex.length !== 6) return 'vbBlack'; // Default color
    const r = parseInt(hex.substring(0, 2), 16);
    const g = parseInt(hex.substring(2, 4), 16);
    const b = parseInt(hex.substring(4, 6), 16);
    return `RGB(${r}, ${g}, ${b})`;
}

function getVbsHorizontalAlignment(alignment: string | undefined): string {
    switch(alignment) {
        case 'left': return 'xlLeft';
        case 'center': return 'xlCenter';
        case 'right': return 'xlRight';
        case 'fill': return 'xlFill';
        case 'justify': return 'xlJustify';
        case 'centerContinuous': return 'xlCenterAcrossSelection';
        default: return '';
    }
}

function getVbsVerticalAlignment(alignment: string | undefined): string {
    switch(alignment) {
        case 'top': return 'xlTop';
        case 'center': return 'xlCenter';
        case 'bottom': return 'xlBottom';
        case 'justify': return 'xlJustify';
        case 'distributed': return 'xlDistributed';
        default: return '';
    }
}


function generateVbsHeader(toolName: string): string {
    return `Option Explicit

' VBScript generated by Excel Power Tools - ${toolName}
' This script will perform actions on the currently active Excel workbook.

Dim objExcel, objWorkbook, objSheet, i
On Error Resume Next
Set objExcel = GetObject(, "Excel.Application")
If Err.Number <> 0 Then
    Set objExcel = CreateObject("Excel.Application")
End If
On Error GoTo 0

objExcel.Visible = True
Set objWorkbook = objExcel.ActiveWorkbook

If objWorkbook Is Nothing Then
    MsgBox "No active workbook found. Please open the workbook you want to process.", vbExclamation, "No Workbook Active"
    WScript.Quit
End If
`;
}

function generateVbsFooter(): string {
    return `
Set objSheet = Nothing
Set objWorkbook = Nothing
Set objExcel = Nothing

MsgBox "Processing complete.", vbInformation, "Finished"
`;
}

export function generateDuplicateFinderVbs(
    sheetNames: string[],
    keyColumnsIdentifiers: string,
    updateColumnIdentifier: string,
    updateValue: string,
    headerRow: number,
    highlightColor?: string,
    conditionalColumnIdentifier?: string
): string {
    if (sheetNames.length === 0 || !keyColumnsIdentifiers || !updateColumnIdentifier) {
        return "' Configure options to generate the VBScript preview.";
    }

    const highlightRgb = highlightColor ? getVbsColor(highlightColor) : '';

    let script = generateVbsHeader("Duplicate Finder");
    script += `
Dim dict, key, R, lastRow, updateValue, headerRow, cellValue
Dim keyCols, updateCol, conditionalCol, col, colIndex, headers, compositeKey
Set dict = CreateObject("Scripting.Dictionary")
updateValue = "${updateValue.replace(/"/g, '""')}"
headerRow = ${headerRow}
keyCols = Split("${keyColumnsIdentifiers}", ",")
`;

    sheetNames.forEach(sheetName => {
        const safeSheetName = sheetName.replace(/"/g, '""');
        script += `
' --- Processing Sheet: ${safeSheetName} ---
On Error Resume Next
Set objSheet = objWorkbook.Worksheets("${safeSheetName}")
On Error GoTo 0

If Not objSheet Is Nothing Then
    dict.RemoveAll
    
    ' Resolve column indices from names or letters
    ReDim headers(objSheet.UsedRange.Columns.Count - 1)
    For col = 1 To objSheet.UsedRange.Columns.Count
        headers(col - 1) = LCase(Trim(CStr(objSheet.Cells(headerRow, col).Value)))
    Next
    
    For i = 0 To UBound(keyCols)
        keyCols(i) = Trim(keyCols(i))
        On Error Resume Next
        colIndex = -1
        colIndex = Application.WorksheetFunction.Match(keyCols(i), objSheet.Rows(headerRow), 0)
        If Err.Number <> 0 Then ' Not found by name, try parsing as letter/number
             If IsNumeric(keyCols(i)) Then
                colIndex = CInt(keyCols(i))
             Else
                colIndex = objSheet.Range(keyCols(i) & "1").Column
             End If
        End If
        On Error GoTo 0
        keyCols(i) = colIndex
    Next

    On Error Resume Next
    updateCol = Application.WorksheetFunction.Match("${updateColumnIdentifier}", objSheet.Rows(headerRow), 0)
     If Err.Number <> 0 Then
         If IsNumeric("${updateColumnIdentifier}") Then
            updateCol = CInt("${updateColumnIdentifier}")
         Else
            updateCol = objSheet.Range("${updateColumnIdentifier}" & "1").Column
         End If
    End If

    ${conditionalColumnIdentifier ? `
    conditionalCol = -1
    On Error Resume Next
    conditionalCol = Application.WorksheetFunction.Match("${conditionalColumnIdentifier}", objSheet.Rows(headerRow), 0)
    If Err.Number <> 0 Then
         If IsNumeric("${conditionalColumnIdentifier}") Then
            conditionalCol = CInt("${conditionalColumnIdentifier}")
         Else
            conditionalCol = objSheet.Range("${conditionalColumnIdentifier}" & "1").Column
         End If
    End If
    ` : ''}
    On Error GoTo 0
    
    lastRow = objSheet.Cells(objSheet.Rows.Count, 1).End(-4162).Row ' xlUp

    ' Loop through all rows to find duplicates
    For R = headerRow + 1 To lastRow
        compositeKey = ""
        For Each col in keyCols
            If col > 0 Then
                compositeKey = compositeKey & objSheet.Cells(R, col).Value & "||"
            End If
        Next
        
        If Len(compositeKey) > 0 Then
            If dict.Exists(compositeKey) Then
                ' This is a duplicate row
                Dim markDuplicate
                markDuplicate = True
                ${conditionalColumnIdentifier ? `
                If conditionalCol > 0 Then
                    If Len(Trim(CStr(objSheet.Cells(R, conditionalCol).Value))) > 0 Then
                        markDuplicate = False
                    End If
                End If
                ` : ''}

                If markDuplicate Then
                    objSheet.Cells(R, updateCol).Value = updateValue
                    ${highlightRgb ? `objSheet.Rows(R).Interior.Color = ${highlightRgb}` : ''}
                End If
            Else
                dict.Add compositeKey, R
            End If
        End If
    Next
End If
`;
    });
    script += generateVbsFooter();
    return script;
}

export function generateEmptyCellFinderVbs(
    sheetNames: string[],
    columnsToCheck: string,
    columnsToIgnore: string,
    headerRow: number,
    highlightColor?: string
): string {
    if (sheetNames.length === 0 || !columnsToCheck || !highlightColor) {
        return "' Configure options to generate the VBScript preview. Highlighting must be enabled.";
    }

    const highlightRgb = getVbsColor(highlightColor);
    let script = generateVbsHeader("Empty Cell Finder");
    script += `
Dim R, lastRow, col
Dim dict, item, checkCols, ignoreCols, finalCols, colNum
`;
    sheetNames.forEach(sheetName => {
        const safeSheetName = sheetName.replace(/"/g, '""');
        script += `
' --- Processing Sheet: ${safeSheetName} ---
On Error Resume Next
Set objSheet = objWorkbook.Worksheets("${safeSheetName}")
On Error GoTo 0
If Not objSheet Is Nothing Then
    lastRow = objSheet.UsedRange.Rows.Count
    Set dict = CreateObject("Scripting.Dictionary")

    ' Populate columns to check
    ${columnsToCheck === '*' ? `
    For col = 1 To objSheet.UsedRange.Columns.Count
        dict.Add CStr(col), True
    Next
    ` : `
    checkCols = Split("${parseSourceColumns(columnsToCheck).map(c => c + 1).join(',')}", ",")
    For Each item In checkCols
        If Trim(item) <> "" Then dict.Add Trim(item), True
    Next
    `}
    
    ' Remove columns to ignore
    ${columnsToIgnore ? `
    ignoreCols = Split("${parseSourceColumns(columnsToIgnore).map(c => c + 1).join(',')}", ",")
    For Each item In ignoreCols
        If dict.Exists(Trim(item)) Then
            dict.Remove Trim(item)
        End If
    Next
    ` : ''}
    
    finalCols = dict.Keys()

    For R = ${headerRow + 1} To lastRow
        For Each item In finalCols
            colNum = CInt(item)
            If IsEmpty(objSheet.Cells(R, colNum)) Or Trim(CStr(objSheet.Cells(R, colNum).Value)) = "" Then
                objSheet.Cells(R, colNum).Interior.Color = ${highlightRgb}
            End If
        Next
    Next
End If
`;
    });
    script += generateVbsFooter();
    return script;
}

export function generateTextFormatterVbs(
    sheetNames: string[],
    config: TextFormatConfig
): string {
    const { searchText, searchMode, matchCase, matchEntireCell, style, range } = config;
    if (sheetNames.length === 0 || searchText.length === 0) {
        return "' Configure sheets and text to find to generate the VBScript preview.";
    }
    
    let script = generateVbsHeader("Text Formatter");
    script += `
Dim cell, term, regEx, cellValue
`;
    if (searchMode === 'regex') {
        script += `
Set regEx = CreateObject("VBScript.RegExp")
regEx.Global = True
regEx.IgnoreCase = ${matchCase ? 'False' : 'True'}
`;
    }

    sheetNames.forEach(sheetName => {
        const safeSheetName = sheetName.replace(/"/g, '""');
        script += `
' --- Processing Sheet: ${safeSheetName} ---
On Error Resume Next
Set objSheet = objWorkbook.Worksheets("${safeSheetName}")
On Error GoTo 0
If Not objSheet Is Nothing Then
    Dim searchArea
    ${range ? `Set searchArea = objSheet.Range("${range.startCol}${range.startRow}:${range.endCol}${range.endRow}")` : `Set searchArea = objSheet.UsedRange`}
    
    For Each cell In searchArea.Cells
        If Not IsEmpty(cell) Then
            cellValue = CStr(cell.Value)
            Dim isMatch
            isMatch = False
`;
        searchText.forEach(term => {
            const safeTerm = term.replace(/"/g, '""');
            let condition: string;
            
            if (searchMode === 'regex') {
                const pattern = matchEntireCell ? `^${safeTerm}$` : safeTerm;
                condition = `regEx.Pattern = "${pattern}"\n            If regEx.Test(cellValue) Then isMatch = True`;
            } else {
                const compareFunc = matchCase ? 'cellValue' : 'LCase(cellValue)';
                const termValue = matchCase ? `"${safeTerm}"` : `LCase("${safeTerm}")`;
                const textCondition = matchEntireCell 
                    ? `${compareFunc} = ${termValue}` 
                    : `InStr(1, ${compareFunc}, ${termValue}, ${matchCase ? '0' : '1'}) > 0`;
                condition = `If ${textCondition} Then isMatch = True`;
            }

            script += `
            If Not isMatch Then
                ${condition}
            End If
`;
        });
        
        script += `
            If isMatch Then
`;
        if (style.font) {
            if (style.font.bold !== undefined) script += `                cell.Font.Bold = ${style.font.bold ? 'True' : 'False'}\n`;
            if (style.font.italic !== undefined) script += `                cell.Font.Italic = ${style.font.italic ? 'True' : 'False'}\n`;
            if (style.font.underline !== undefined) script += `                cell.Font.Underline = ${style.font.underline ? 'xlUnderlineStyleSingle' : 'xlUnderlineStyleNone'}\n`;
            if (style.font.name) script += `                cell.Font.Name = "${style.font.name}"\n`;
            if (style.font.size) script += `                cell.Font.Size = ${style.font.size}\n`;
            if (style.font.color) script += `                cell.Font.Color = ${getVbsColor(style.font.color)}\n`;
        }
        if (style.fill && style.fill.color) {
            script += `                cell.Interior.Color = ${getVbsColor(style.fill.color)}\n`;
        }
        if (style.alignment) {
            const hAlign = getVbsHorizontalAlignment(style.alignment.horizontal);
            const vAlign = getVbsVerticalAlignment(style.alignment.vertical);
            if (hAlign) script += `                cell.HorizontalAlignment = ${hAlign}\n`;
            if (vAlign) script += `                cell.VerticalAlignment = ${vAlign}\n`;
        }
        script += `            End If
`;
        script += `
        End If
    Next
End If
`;
    });
    script += generateVbsFooter();
    return script;
}
